# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bullet',
        ),
        migrations.AddField(
            model_name='project',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
