# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170716_0229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='MyProject',
        ),
    ]
