# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymsg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='receiver',
            field=models.CharField(max_length=50, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='text',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Subject'),
        ),
    ]
