# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0004_auto_20170729_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res_basic',
            name='email',
            field=models.CharField(blank=True, default='a', max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='res_basic',
            name='phone',
            field=models.CharField(blank=True, default='a', max_length=100, null=True, verbose_name='phone'),
        ),
    ]
