# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 22:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0006_auto_20170729_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res_basic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
