# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0007_auto_20170729_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='res_basic',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='address'),
        ),
    ]
