# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0008_res_basic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='res_basic',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='res_basic',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='res_basic',
            name='zipcode',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='zipcode'),
        ),
        migrations.AlterField(
            model_name='res_basic',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='title'),
        ),
    ]
