# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0009_auto_20170730_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res_basic',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='zipcode'),
        ),
    ]
